version: '3.8'

services:
  api:
    build: .
    volumes:
      - ./app:/app  # live reload
    ports:
      - "8000:10000"  # maps localhost:8000 to container:10000
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:latest
    command: http api:10000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - api
    env_file:
      - .env
